
apiVersion: v1
kind: ServiceAccount
metadata:
  name: login-app
  labels:
    app: login-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-app
  template:
    metadata:
      labels:
        app: login-app
    spec:
      serviceAccountName: login-app
      containers:
        - name: login-app
          image: login-app:0.1.0-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
              name: http
          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 9000
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - name: secret
              mountPath: "/etc/secrets"
              readOnly: true
      volumes:
        - name: secret
          secret:
            secretName: functionalscala2021
---
apiVersion: v1
kind: Service
metadata:
  name: login-app
spec:
  selector:
    app: login-app
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: http