apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externalsecrets.jkobejs.github.io
spec:
  group: jkobejs.github.io
  scope: Namespaced

  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          required:
            - spec
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                  description: Secret type
                  enum:
                    - Opaque
            status:
              type: object
              properties:
                lastSync:
                  type: string
                  format: date-time
                state:
                  type: string
                  enum:
                    - UNSYNCED
                    - SYNCED
                  default: UNSYNCED
      additionalPrinterColumns:
        - jsonPath: .status.lastSync
          name: Last Sync
          type: date
        - jsonPath: .status.state
          name: status
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date

  names:
    shortNames:
      - es
    kind: ExternalSecret
    plural: externalsecrets
    singular: externalsecret
